find_path(OPENSSL_INCLUDE_DIR NAMES ssl.h PATHS ${CONAN_INCLUDE_DIRS_OPENSSL} NO_CMAKE_FIND_ROOT_PATH)
find_library(OPENSSL_LIBRARY NAMES ${CONAN_LIBS_OPENSSL} PATHS ${CONAN_LIB_DIRS_OPENSSL} NO_CMAKE_FIND_ROOT_PATH)

MESSAGE("** OPENSSL ALREADY FOUND BY CONAN!")
SET(OPENSSL_FOUND TRUE)
MESSAGE("** FOUND OPENSSL:  ${OPENSSL_LIBRARY}")
MESSAGE("** FOUND OPENSSL INCLUDE:  ${OPENSSL_INCLUDE_DIR}")

set(OPENSSL_INCLUDE_DIRS ${OPENSSL_INCLUDE_DIR})
set(OPENSSL_LIBRARIES ${OPENSSL_LIBRARY})

mark_as_advanced(OPENSSL_LIBRARY OPENSSL_INCLUDE_DIR)
